name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:

        # Paso 1: Descarga el código fuente del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

        # Paso 2: Inicia sesión en el registro de contenedores de GitHub (GHCR) usando credenciales automáticas
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # Paso 3: Extrae metadatos para la imagen Docker (etiquetas y labels)
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

        # Paso 4: Muestra los archivos del repositorio (lo use para depuración)
      - name: Show repo files
        run: ls -R



        # Paso 5: Construye y publica la imagen Docker en GHCR usando los metadatos extraídos
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile   
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
